# Users
## Create User
POST http://localhost:6000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "password": "shining",
  "userType": "normal"
}

###

## Авторизовать пользователя

POST http://localhost:6000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}
