# Offers
## Get list of offers
GET http://localhost:6000/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новую категорию
POST http://localhost:6000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "69200d3b792b6714899391c6"
}

###
